# Generated by Django 3.1.7 on 2021-03-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('speed', models.IntegerField()),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
